-- EF1/RG1 — Le formateur ouvre une session et obtient un code de présence.
-- Conforme au D2 : clés primaires bigint auto-incrément générées par la base,
-- jamais d'UUID applicatif (section 8 du cahier des charges).

CREATE TABLE promotion (
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(255) NOT NULL
);

-- "session" est un mot réservé en SQL standard : la table s'appelle session_cours.
CREATE TABLE session_cours (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    promotion_id  BIGINT NOT NULL REFERENCES promotion (id),
    titre         VARCHAR(255) NOT NULL,
    code          VARCHAR(6)   NOT NULL,
    ouverture_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    expiration_at TIMESTAMP WITH TIME ZONE NOT NULL,
    statut        VARCHAR(16)  NOT NULL,
    CONSTRAINT uq_session_cours_code UNIQUE (code),
    CONSTRAINT ck_session_cours_statut CHECK (statut IN ('OUVERTE', 'CLOTUREE'))
);

CREATE INDEX idx_session_cours_promotion ON session_cours (promotion_id);
CREATE INDEX idx_session_cours_code ON session_cours (code);
