-- EF2/EF3 (RG2, RG13) : un étudiant de la promotion marque sa présence à une session
-- via le code éphémère. L'unicité (session, étudiant) rend le 409 DEJA_PRESENT
-- vérifiable en base et pas seulement dans le code de service.

CREATE TABLE etudiant (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    promotion_id  BIGINT NOT NULL REFERENCES promotion (id),
    nom           VARCHAR(255) NOT NULL
);

CREATE INDEX idx_etudiant_promotion ON etudiant (promotion_id);

CREATE TABLE presence (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id    BIGINT NOT NULL REFERENCES session_cours (id),
    etudiant_id   BIGINT NOT NULL REFERENCES etudiant (id),
    source        VARCHAR(16) NOT NULL,
    marquee_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_presence_source CHECK (source IN ('ETUDIANT', 'FORMATEUR')),
    -- Un étudiant ne peut être présent qu'une fois par session (EF3, RG13)
    CONSTRAINT uq_presence_session_etudiant UNIQUE (session_id, etudiant_id)
);
