-- EF6/EF7/EF8 : un étudiant dépose le lien de son exercice pour une session ;
-- un relecteur est assigné au dépôt, au hasard parmi les présents (RG4, RG5, RG6).

CREATE TABLE exercice (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id    BIGINT NOT NULL REFERENCES session_cours (id),
    etudiant_id   BIGINT NOT NULL REFERENCES etudiant (id),
    lien          VARCHAR(2048) NOT NULL,
    statut        VARCHAR(32) NOT NULL,
    depose_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_exercice_statut CHECK (statut IN ('EN_ATTENTE_RELECTURE', 'RELU')),
    -- Un seul exercice par étudiant et par session : le 409 EXERCICE_DEJA_DEPOSE
    -- est aussi garanti en base, le remplacement passe par PUT (EF7)
    CONSTRAINT uq_exercice_session_etudiant UNIQUE (session_id, etudiant_id)
);

CREATE TABLE relecture (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exercice_id   BIGINT NOT NULL REFERENCES exercice (id),
    relecteur_id  BIGINT NOT NULL REFERENCES etudiant (id),
    note          INTEGER,
    commentaire   VARCHAR(4000),
    rendue_at     TIMESTAMP WITH TIME ZONE,
    -- RG5 : exactement un relecteur par exercice
    CONSTRAINT uq_relecture_exercice UNIQUE (exercice_id),
    -- RG8 : note entière entre 0 et 20 (nulle tant que la relecture n'est pas rendue)
    CONSTRAINT ck_relecture_note CHECK (note IS NULL OR note BETWEEN 0 AND 20)
);

-- EF9 et EF16 : liste des relectures d'un relecteur, relectures en attente
CREATE INDEX idx_relecture_relecteur ON relecture (relecteur_id);
